services:
  app:
    image: Romira/zenita
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    working_dir: /var/www/app
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
      IMAGE_BASE_URL: http://localhost:8080
    ports:
      - "8080:80"
    volumes:
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./apache/php/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www/app
    depends_on:
      - db
  db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql
      - ./db/init.d:/docker-entrypoint-initdb.d

volumes:
  db-data:
